version: "3.9"
services:

  db:
    build: "./database-image"
    image: "microservices-db"
    container_name: "postgres-container-wallet-read-service"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql1020
      - POSTGRES_DB=wallet-read-service
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 128m
    # networks:
    #   - mybridge
